# Generated by Django 5.2.7 on 2025-10-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('table_num', models.IntegerField(default=0)),
                ('favorite', models.IntegerField(default=8)),
            ],
        ),
    ]
