# Generated by Django 5.1.6 on 2025-10-29 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matching_app", "0002_person"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
