# Generated by Django 5.2.8 on 2025-11-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='weight',
        ),
        migrations.AddField(
            model_name='person',
            name='bg_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
    ]
